# telnet.netkit
# Autogenerated from man page /usr/share/man/man1/telnet.netkit.1.gz
complete -c 'telnet.netkit' -s 4 -d 'Force IPv4 address resolution'
complete -c 'telnet.netkit' -s 6 -d 'Force IPv6 address resolution'
complete -c 'telnet.netkit' -s 8 -d 'Request 8-bit operation'
complete -c 'telnet.netkit' -s E -d 'Disables the escape character functionality; that is, sets the escape charact…'
complete -c 'telnet.netkit' -s L -d 'Specifies an 8-bit data path on output'
complete -c 'telnet.netkit' -s a -d 'Attempt automatic login'
complete -c 'telnet.netkit' -s b -d 'Use bind(2) on the local socket to bind it to a specific local address'
complete -c 'telnet.netkit' -s d -d 'Sets the initial value of the debug toggle to TRUE'
complete -c 'telnet.netkit' -s r -d 'Emulate rlogin 1.  In this mode, the default escape character is a tilde'
complete -c 'telnet.netkit' -s S -d 'Sets the IP type-of-service (TOS) option for the telnet connection to the val…'
complete -c 'telnet.netkit' -s e -d 'Sets the escape character to escapechar'
complete -c 'telnet.netkit' -s l -d 'Specify user as the user to log in as on the remote system'
complete -c 'telnet.netkit' -s n -d 'Opens tracefile for recording trace information'

